# Generated by Django 4.0.1 on 2022-01-06 12:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rcoffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('admins', django.db.models.manager.Manager()),
            ],
        ),
    ]
