# Generated by Django 4.0.1 on 2022-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcoffee', '0004_alter_user_managers_alter_user_about_alter_user_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(to='rcoffee.Company'),
        ),
    ]
