# Generated by Django 4.0.1 on 2022-01-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcoffee', '0005_user_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
