# Generated by Django 4.0.1 on 2022-01-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcoffee', '0006_rename_admin_id_company_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
