# Generated by Django 4.0.1 on 2022-01-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcoffee', '0007_alter_company_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Team',
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(to='rcoffee.Team'),
        ),
    ]
