# Generated by Django 4.0.1 on 2022-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcoffee', '0008_rename_company_team_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
