# Generated by Django 4.0.1 on 2022-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcoffee', '0010_rename_is_admin_user_is_super_admin_user_is_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='feedback_a',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='feedback_b',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
