# Generated by Django 4.0.1 on 2022-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
